'use client';

import { motion } from 'framer-motion';
import { Check, Crown, Zap, Bot, Shield } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/card';

const plans = [
  {
    name: 'FREE',
    price: '0',
    priceSol: '0',
    description: 'Start your journey',
    features: [
      'Access to 3 basic bots',
      'Public channel signals',
      'Basic MEV alerts',
      'Community support',
    ],
    icon: Zap,
    color: 'from-gray-500 to-gray-600',
    popular: false,
  },
  {
    name: 'ALPHA',
    price: '29',
    priceSol: '0.2',
    description: 'For serious traders',
    features: [
      'Access to 8 advanced bots',
      'Private alpha channel',
      'Real-time MEV protection',
      'Portfolio analytics',
      'Priority support',
      'Weekly strategy calls',
    ],
    icon: Bot,
    color: 'from-cyan-500 to-blue-500',
    popular: true,
  },
  {
    name: 'GOD TIER',
    price: '99',
    priceSol: '0.7',
    description: 'Institutional grade',
    features: [
      'All 12 bots unlocked',
      'Custom bot development',
      '1-on-1 strategy sessions',
      'API access',
      'White-label solutions',
      'Direct line to team',
      'Revenue sharing program',
    ],
    icon: Crown,
    color: 'from-purple-500 via-pink-500 to-rose-500',
    popular: false,
  },
];

export default function SubscriptionPage() {
  return (
    <div className="min-h-screen py-20 px-4">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-6xl font-bold mb-4">Choose Your Power</h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Unlock the full potential of ICEGODS. Pay with SOL or fiat.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
          {plans.map((plan, i) => (
            <motion.div
              key={plan.name}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
            >
              <Card className={`relative h-full ${plan.popular ? 'border-cyan-500/50' : ''}`}>
                {plan.popular && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-4 py-1 rounded-full text-sm font-bold">
                    MOST POPULAR
                  </div>
                )}
                
                <CardHeader>
                  <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${plan.color} flex items-center justify-center mb-4`}>
                    <plan.icon className="w-6 h-6 text-white" />
                  </div>
                  <CardTitle className="text-2xl">{plan.name}</CardTitle>
                  <p className="text-gray-400 text-sm">{plan.description}</p>
                </CardHeader>
                
                <CardContent>
                  <div className="mb-6">
                    <span className="text-4xl font-bold">${plan.price}</span>
                    <span className="text-gray-400">/mo</span>
                    <div className="text-sm text-cyan-400">or {plan.priceSol} SOL</div>
                  </div>

                  <ul className="space-y-3 mb-8">
                    {plan.features.map((feature) => (
                      <li key={feature} className="flex items-start gap-2 text-sm">
                        <Check className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                        <span className="text-gray-300">{feature}</span>
                      </li>
                    ))}
                  </ul>

                  <Button 
                    className="w-full" 
                    variant={plan.popular ? 'default' : 'outline'}
                  >
                    {plan.price === '0' ? 'Get Started' : 'Subscribe Now'}
                  </Button>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* Revenue Share */}
        <div className="mt-20 glass rounded-2xl p-8 max-w-4xl mx-auto">
          <div className="flex items-center gap-4 mb-4">
            <Shield className="w-8 h-8 text-emerald-400" />
            <h3 className="text-2xl font-bold">Revenue Sharing Program</h3>
          </div>
          <p className="text-gray-400 mb-4">
            GOD Tier members earn 20% of platform fees generated by their referrals. 
            Build your network, earn passive income.
          </p>
          <div className="text-sm text-gray-500">
            Platform wallet: 8dtu...Hbxy • ETH: 0x20d...70fc1
          </div>
        </div>
      </div>
    </div>
  );
}
